git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
gui:
  border: single
  showCommandLog: false
  skipDiscardChangeWarning: true
  # kanagawa
  theme:
    selectedLineBgColor:
      - "#223249"
    searchingActiveBorderColor:
      - "#ff9e3b"
      - "bold"
    optionsTextColor:
      - "#7e9cd8"
    inactiveBorderColor:
      - "#54546d"
    defaultFgColor:
      - "#dcd7ba"
    cherryPickedCommitFgColor:
      - "#7e9cd8"
    cherryPickedCommitBgColor:
      - "#e6c384"
    activeBorderColor:
      - "#ff9e3b"
      - "bold"
    unstagedChangesColor:
      - "#e82424"
  nerdFontsVersion: "3"
keybinding:
  universal:
    filteringMenu: <disabled>
os:
  editPreset: "nvim-remote"

  # cyberdream
  # theme:
  #   activeBorderColor:
  #     - "#5ef1ff"
  #   inactiveBorderColor:
  #     - "#7b8496"
  #   searchingActiveBorderColor:
  #     - "#ff5ef1"
  #   optionsTextColor:
  #     - "#3c4048"
  #   selectedLineBgColor:
  #     - "#3c4048"
  #   cherryPickedCommitBgColor:
  #     - "#3c4048"
  #   cherryPickedCommitFgColor:
  #     - "#ff5ea0"
  #   unstagedChangesColor:
  #     - "#ffbd5e"
  #   defaultFgColor:
  #     - "#ffffff"
