#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x nm-applet > /dev/null || nm-applet &
pgrep -x polybar > /dev/null || ~/dotfiles/scripts/polybar &
pgrep -x copyq > /dev/null || copyq &
pgrep -x lxsession > /dev/null || lxsession &
nitrogen --restore
xsetroot -cursor_name left_ptr
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1

# Workspaces
bspc monitor -d I II III IV V VI

# Configs
bspc config border_width        2
bspc config window_gap          6
bspc config top_padding         30

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle  false

bspc config ignore_ewmh_focus    true

bspc config external_rules_command "$HOME/"dotfiles/bspwm/.config/bspwm/external_rules

bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true

bspc config normal_border_color      "#30363f"
bspc config active_border_color      "#4fa6ed"
bspc config focused_border_color     "#4fa6ed"
bspc config presel_feedback_color    "#4fa6ed"
bspc config urgent_border_color      "#e55561"

