#! /bin/sh

# Autostart
~/dotfiles/bspwm/.config/bspwm/autostart

# Workspaces
bspc monitor -d I II III IV V VI VII VIII IX X

# Configs
bspc config border_width        2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle  false

bspc config ignore_ewmh_focus    true

bspc config external_rules_command "$HOME/"dotfiles/bspwm/.config/bspwm/external_rules

