#!/usr/bin/env ruby
#
# bspwm: external_rules_command

# hostname
# hostname = `hostname`.strip
# arguments
id = ARGV[0]
clazz = ARGV[1]
instance = ARGV[2]
# xprop
xprop = `xprop -id #{id}`.strip
# role and title
matches = xprop.match(/(?:^WM_WINDOW_ROLE\(STRING\) = \"(.*)\"$)|(?:^_NET_WM_NAME\(UTF8_STRING\) = \"(.*)\")/)
role = matches.nil? ? '' : matches[1]
title = matches.nil? ? '' : matches[2]
# process name
process = `ps -p "$(xdo pid #{id})" -o comm= 2>/dev/null`.strip

# generic rules
case clazz
when 'Brave-browser'
  print 'desktop=^1'
when 'Nightly', 'FirefoxNightly', 'LibreWolf'
  print 'desktop=^1' if instance == 'Navigator'
  case instance
  when 'Devtools', 'Dialog', 'GtkFileChooserDialog', 'Prompt'
    print 'state=floating'
  else
    print 'state=tiled'
  end
  case role
  when 'GtkFileChooserDialog'
    print 'state=floating'
  end

when 'Gnome-calculator', 'Orage', 'Nitrogen', 'Enpass', 'Nm-connection-editor', 'Pavucontrol'
  print 'state=floating'

when 'jetbrains-idea', 'jetbrains-phpstorm', 'VSCodium', 'code-oss'
  print 'desktop=^2'
  print 'state=floating' if title == 'win0'

when 'Chromium', 'Google-chrome'
  print 'desktop=^1'
  print 'state=floating' if role == 'pop-up'

when 'DBeaver', 'Postman', 'Dynalist'
  print 'desktop=^4'

when 'Spotify'
  print 'desktop=^5'

when 'Slack', 'discord'
  print 'desktop=^5'

when 'Alacritty'
  print 'desktop=^2' if title.include? 'nvim'

when ''
  case process
  when 'spotify'
    print 'desktop=^5'
  end
end

print ' '
