gui:
  border: rounded
  # kanagawa
  theme:
    selectedLineBgColor:
      - "#2d4f67"

  # cyberdream
  # theme:
  #   activeBorderColor:
  #     - "#5ef1ff"
  #   inactiveBorderColor:
  #     - "#7b8496"
  #   selectedLineBgColor:
  #     - "#3c4048"
  #   optionsTextColor:
  #     - "#3c4048"
