[opener]
zathura = [{run = 'zathura "$@"', desc = "zathura", block = true, for = "unix"}]
imv = [{run = 'imv "$@"', desc = "imv", block = true, for = "unix"}]

[open]
prepend_rules = [
    {mime = "application/pdf", use = ["zathura"]},
    {mime = "image/*", use = ["imv"]},
]
