[opener]
zathura = [{run = 'zathura "$@"', desc = "zathura", orphan = true, for = "unix"}]
imv = [{run = 'imv "$@"', desc = "imv", orphan = true, for = "unix"}]
edit = [{ run = 'nvim "$@"', block = true, for = "unix" }]

[open]
prepend_rules = [
    {mime = "application/pdf", use = ["zathura"]},
    {mime = "image/*", use = ["imv"]},
]
