[opener]
zathura = [{run = 'zathura "$@"', desc = "zathura", block = true, for = "unix"}]
sxiv = [{run = 'sxiv "$@"', desc = "sxiv", block = true, for = "unix"}]

[open]
prepend_rules = [
    {mime = "application/pdf", use = ["zathura"]},
    {mime = "image/*", use = ["sxiv"]},
]
