#!/bin/bash

apt-get update

apt-get install -y \
    stow \
    zsh \
    meld \
    xfce4-clipman-plugin \
    xfce4-datetime-plugin \
    htop \
    screenfetch \
    ack \
    pasystray \
    catfish \
    fonts-roboto \
    arc-theme \
    dh-autoreconf \
    software-properties-common

wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/install-papirus-root.sh | sh

# Update font cache
fc-cache

# Change default shell to zsh
chsh -s /bin/zsh
