-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(ff4e66)",
			inactive_border = "rgb(f57385)",
		},
	},
	group = {
		col = {
			border_active = "rgb(ff4e66)",
			border_inactive = "rgb(f57385)",
			border_locked_active = "rgb(ff4e66)",
			border_locked_inactive = "rgb(f57385)",
		},
		groupbar = {
			col = {
				active = "rgb(ff4e66)",
				inactive = "rgb(f57385)",
				locked_active = "rgb(ff4e66)",
				locked_inactive = "rgb(f57385)",
			},
		},
	},
})
