-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "catppuccin-macchiato-dark-cursors")
hl.env("XCURSOR_THEME", "catppuccin-macchiato-dark-cursors")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_SIZE", "24")
