[[profile]]
name = "default"

[[profile.output]]
enable = true
search = ["m=0x14E5", "s=", "v=Chimei Innolux Corporation"]
mode = "1920x1080@60.008Hz"
position = "0,0"
scale = 1.0
transform = "normal"
adaptive_sync = false

