vim.pack.add { 'https://github.com/folke/which-key.nvim' }
require('which-key').setup {
  preset = 'helix',
  delay = 500,
  icons = {
    mappings = false,
  },
  spec = {
    { '<leader>a', group = 'AI' },
    { '<leader>b', group = 'Buffer' },
    { '<leader>c', group = 'Code' },
    { '<leader>cr', group = 'Rails' },
    { '<leader>cs', group = 'Snippets' },
    { '<leader>d', group = 'Debug' },
    { '<leader>f', group = 'Find and Replace' },
    { '<leader>g', group = 'Git' },
    { '<leader>gp', group = 'Github PRs' },
    { '<leader>h', group = 'Git Hunk' },
    { '<leader>H', group = 'HTTP Client' },
    { '<leader>l', group = 'LSP' },
    { '<leader>o', group = 'Options' },
    { '<leader>oP', group = 'Profiler' },
    { '<leader>oa', group = 'Autoformatting' },
    { '<leader>O', group = 'Obsidian' },
    { '<leader>p', group = 'Paste' },
    { '<leader>r', group = 'Runner' },
    { '<leader>rl', group = 'Last Task' },
    { '<leader>s', group = 'Search' },
    { '<leader>t', group = 'Test' },
    { '<leader>td', group = 'Debug Test' },
    { '<leader>w', group = 'Window' },
  },
}
