
[[Snippets]]
  Description = "Remove duplicated lines (sorting)"
  Output = ""
  Tag = []
  command = "sort -u <file> > <result>"

[[Snippets]]
  Description = "Remove duplicated lines (order preserved)"
  Output = ""
  Tag = []
  command = "cat -n <file> | sort -uk2 | sort -nk1 | cut -f2-"

[[Snippets]]
  Description = "Remove lines from file1 that are found in file2"
  Output = ""
  Tag = []
  command = "grep -F -v -x -f <file2> <file1>"

[[Snippets]]
  Description = "Ruby debug"
  Output = ""
  Tag = []
  command = "/usr/bin/zsh -c \"bash -c '~/.rvm/bin/rvm ruby-2.3.8 do ~/.rvm/rubies/ruby-2.3.8/bin/ruby ~/.rvm/gems/ruby-2.3.8/gems/ruby-debug-ide-2.3.1/bin/rdebug-ide --key-value --step-over-in-blocks --disable-int-handler --evaluation-timeout 10 --evaluation-control --time-limit 100 --memory-limit 0 --rubymine-protocol-extensions --port 32943 --host 0.0.0.0 --dispatcher-port 38073 -- ~/dev/src/github.com/cgimenes/lms/bin/rails server -b 0.0.0.0 -p 3000 -e local_development'\""

[[Snippets]]
  Description = "Confuse people SSHing to your host with a redirect back to theirs"
  Output = ""
  Tag = []
  command = "socat -d -d TCP-L:22,reuseaddr,fork SYSTEM:\"nc \\$SOCAT_PEERADDR 22\""

[[Snippets]]
  Description = "Wireshark over SSH"
  Output = ""
  Tag = []
  command = "wireshark -k -i <(ssh sheep@46.101.153.159 \"tshark -F pcap -w - -f 'not tcp port 22'\")"

[[Snippets]]
  Description = "Get all machines answering ICMP within an IP range"
  Output = ""
  Tag = []
  command = "nmap -sn 192.168.0.0/24"

[[Snippets]]
  Description = "Python 3 HTTP server"
  Output = ""
  Tag = []
  command = "python3 -m http.server"

[[Snippets]]
  Description = "Python 2 HTTP server"
  Output = ""
  Tag = []
  command = "python2 -m SimpleHTTPServer"

[[Snippets]]
  Description = "MD5SUM every file in a folder and save in a file (used for diffying two directories)"
  Output = ""
  Tag = []
  command = "find <dir> -type f -exec md5sum {} + | sort -k 2 > <dir>.txt"

[[Snippets]]
  Description = "Find commit which deleted a file"
  Output = ""
  Tag = []
  command = "git log --all -1 -- <file>"

[[Snippets]]
  Description = "Use FZF to set kubectl current namespace"
  Output = ""
  Tag = []
  command = "kubectl get namespace --no-headers | fzf | awk '{ print $1}' | xargs -I {} kubectl config set-context --current --namespace={}"

[[Snippets]]
  Description = "Use FZF to set kubectl current context"
  Output = ""
  Tag = []
  command = "kubectl config get-contexts --no-headers | fzf | awk '{ print $1}' | xargs kubectl config use-context"

[[Snippets]]
  Description = "Crypto Exchange Rates"
  Output = ""
  Tag = []
  command = "curl 'rate.sx/<coin>?qF'"

[[Snippets]]
  Description = "Weather"
  Output = ""
  Tag = []
  command = "curl 'wttr.in/<city>?Fq'"

[[Snippets]]
  Description = "psql select to CSV"
  Output = ""
  Tag = []
  command = "\\copy (select * from foo) To '/tmp/test.csv' With CSV DELIMITER ',' HEADER"

[[Snippets]]
  Description = "cat to 0x0.st"
  Output = ""
  Tag = []
  command = "cat <file> | curl -F'file=@-' https://0x0.st"

[[Snippets]]
  Description = "Send file to 0x0.st"
  Output = ""
  Tag = []
  command = "curl -F'file=@<file>' https://0x0.st"

[[Snippets]]
  Description = "Terminate celery task"
  Output = ""
  Tag = []
  command = "celery -A <path=config> control terminate SIGKILL <id>"

[[Snippets]]
  Description = "Dump DBeaver passwords"
  Output = ""
  Tag = []
  command = "openssl aes-128-cbc -d -K babb4a9f774ab853c96c2d653dfe544a -iv 00000000000000000000000000000000 -in ~/.local/share/DBeaverData/workspace6/General/.dbeaver/credentials-config.json | dd bs=1 skip=16 2>/dev/null"
